/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MeRouteImport } from './routes/me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalligraphersIndexRouteImport } from './routes/calligraphers.index'
import { Route as CharactersIdRouteImport } from './routes/characters.$id'
import { Route as CalligraphersIdRouteImport } from './routes/calligraphers.$id'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalligraphersIndexRoute = CalligraphersIndexRouteImport.update({
  id: '/calligraphers/',
  path: '/calligraphers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CalligraphersIdRoute = CalligraphersIdRouteImport.update({
  id: '/calligraphers/$id',
  path: '/calligraphers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/calligraphers/$id': typeof CalligraphersIdRoute
  '/characters/$id': typeof CharactersIdRoute
  '/calligraphers/': typeof CalligraphersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/calligraphers/$id': typeof CalligraphersIdRoute
  '/characters/$id': typeof CharactersIdRoute
  '/calligraphers': typeof CalligraphersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/calligraphers/$id': typeof CalligraphersIdRoute
  '/characters/$id': typeof CharactersIdRoute
  '/calligraphers/': typeof CalligraphersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/practice'
    | '/search'
    | '/timeline'
    | '/calligraphers/$id'
    | '/characters/$id'
    | '/calligraphers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/practice'
    | '/search'
    | '/timeline'
    | '/calligraphers/$id'
    | '/characters/$id'
    | '/calligraphers'
  id:
    | '__root__'
    | '/'
    | '/me'
    | '/practice'
    | '/search'
    | '/timeline'
    | '/calligraphers/$id'
    | '/characters/$id'
    | '/calligraphers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRoute: typeof MeRoute
  PracticeRoute: typeof PracticeRoute
  SearchRoute: typeof SearchRoute
  TimelineRoute: typeof TimelineRoute
  CalligraphersIdRoute: typeof CalligraphersIdRoute
  CharactersIdRoute: typeof CharactersIdRoute
  CalligraphersIndexRoute: typeof CalligraphersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calligraphers/': {
      id: '/calligraphers/'
      path: '/calligraphers'
      fullPath: '/calligraphers/'
      preLoaderRoute: typeof CalligraphersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calligraphers/$id': {
      id: '/calligraphers/$id'
      path: '/calligraphers/$id'
      fullPath: '/calligraphers/$id'
      preLoaderRoute: typeof CalligraphersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRoute: MeRoute,
  PracticeRoute: PracticeRoute,
  SearchRoute: SearchRoute,
  TimelineRoute: TimelineRoute,
  CalligraphersIdRoute: CalligraphersIdRoute,
  CharactersIdRoute: CharactersIdRoute,
  CalligraphersIndexRoute: CalligraphersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
